### ISSUE TITLE
Pushing OCI image to docker registry?

### ISSUE THREAD

**Issue by amitsaha** [projectatomic/skopeo#168]
This is more of a question: can I use `skopeo` to copy an OCI image (directory containing `refs/` and `blobs/`) to a docker registry?

**Comment by mtrmac** [comment]
Not at the moment, primarily because https://github.com/containers/image does not currently contain an implementation of an OCI source (only a destination; a source should be quite easy to add).  If such a source existed, there might be difficulties with getting a distribution v2 registry to accept OCI images (without conversion to the Docker schema); I believe some patches are floating around for that.

(Closing here, because the missing OCI source, and probably any other needed code, would probably be in https://github.com/containers/image . However, if you are interested, do file an issue there—and of course a PR would be very welcome as well.)

**Comment by fabiand** [comment]
Is there actually any plan to come up with an OCI image registry?
