### ISSUE TITLE
Support remote policy URI

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/skopeo#220]
In a clustered environment we need policy to be shared across the nodes. Also, policy may be dynamically managed via API. Skopeo should support a policy URI that is a GET call to an API.

**Comment by runcom** [comment]
Not sure how I feel about that - I thought skopeo operates on a node and the cluster should instead keep the policy in sync with that the admin wants - not sure of course this is feasible

**Comment by rhatdan** [comment]
Why is this skopeo?  Shouldn't this be handled via Ansible or openshift?

**Comment by runcom** [comment]
> Why is this skopeo? Shouldn't this be handled via Ansible or openshift?

that's what I was thinking - but I understand policies can change overtime and maybe ansible isn't really ok to re-provision a node

**Comment by aweiteka** [comment]
> Shouldn't this be handled via Ansible or openshift?

This is possible with Ansible but it's not really the right tool for potentially dynamic policy. OpenShift, yes, but it would be very awkward for OpenShift to manage landing files on all the nodes, making sure they are in sync, etc. An API call is much safer. It's just JSON.

With policy in an API cluster admins can use external tools (Manage IQ, for example) to manage cluster policy.

**Comment by rhatdan** [comment]
I don't see this as being that dynamic. But perhaps we need to talk to OpenShift/Product Management to see what they think.

**Comment by aweiteka** [comment]
The dynamic use case is derived from developer project self-provisioning, which leads to devs signing their own images. Now what? The entire trust cluster policy needs to be updated to reflect the project.

**Comment by mtrmac** [comment]
skopeo becoming a client to some unspecified API to get remote policies would get us into an area of ever-expanding never-ending integration mess (Does there need to be authentication? Should the GET URL include some data about the host? Things like OpenShift namespaces (about which skopeo has otherwise no idea about)? How many different cluster APIs are there?).

So far I was thinking that we’d have containers/image provide all the underlying functionality, and skopeo just as a trivial wrapper (as it currently is, see https://github.com/projectatomic/skopeo/blob/master/cmd/skopeo/copy.go ) for the non-clustered / manually-managed CLI case.

For cluster integration, the cluster-specific/cluster-aware component (kubelet, ocid, or something) would use a cluster-specific API to get the policy, load it via `containers/image/signature/NewPolicyFromBytes`, and call  `containers/image/copy.Image` with that policy. Or, well, it _could_ also create a temporary file and call the `skopeo` command-line—but _all_ of the cluster specifics would be outside of skopeo.

Would that be a feasible way to handle things?

**Comment by aweiteka** [comment]
> Would that be a feasible way to handle things?

Yes, that would seem to achieve the goal. Do I understand correctly that this capability would be in the implementation of containers/image and not require any features?

**Comment by mtrmac** [comment]
In a (cluster-specific) caller of containers/image, rather.
