### ISSUE TITLE
Only copy a subpart of a source image to a directory

### ISSUE THREAD

**Issue by nlewo** [projectatomic/skopeo#481]
An image can be copied to a directory by using the skopeo `dir`
transport. Currently, all parts (config, layers, manifest) of the
source image are copied to that directory.

I would like be able to only copy subparts of the source
image. These subparts could be layers, configs, or manifests.

Is it already possible?
If not, do you think it would be feasible?
And are you also interested by this feature?

### Use case: Efficient Docker image storage in Nix

Nix has a content addressable store and images are currently
stored as Docker archives. If several images share identical
layers, these layers are duplicated which is really
inefficient. Instead of storing images as tar, I would like to
store them in directories. This would allow us to symlink layers
in order to share them across several images. Note that Nix does
this kind of things pretty well.

Basically, we could use `skopeo inspect` to generate several Nix expressions
to pull the image. Each build expression would use Skopeo to download
a part of the image and let Nix stores them into its own store. If two
images use the same layer, Nix is able to reuse this layer, so the
layer is not duplicated in the Nix store.

### User Interface proposal

We could add some options on the copy command. 
For instance, to copy the first layer of the ubuntu image:
```
skopeo copy --copy-layer sha256:1be7f2b886e89a58e59c4e685fcc5905a26ddef3201f290b96f1eff7d778e122 docker://ubuntu dir:///tmp/first-ubuntu-layer/
```

The `--copy-config` and `--copy-manifest` flags would be used to
copy the image configuration and manifest. Without any of these
flags, all parts of the image would be copyied. Note these
options would only works with the dir transport.

**Comment by rhatdan** [comment]
@mtrmac @runcom WDYT?

**Comment by mtrmac** [comment]
Most of this already exists, to serve exactly the same needs of the `ostree` transport, as `skopeo layers` – but deprecated. It should be very easy to write a similar wrapper around `ImageSource` which extracts exactly the needed blobs, if you don’t need the whole copy machinery (signatures, manifest conversion, compression/decompression) etc.

There is also a somewhat previous conversation in https://github.com/containers/image/pull/218 , and IIRC there may have been a few others; the “copy an image but only actually copy the specified layers” idea has definitely come up before.

---

But, overall, I think it would be much cleaner, and more efficient, to implement the Nix storage directly as an `ImageDestination` in containers/image.  That would allow using the native storage format, with no extra temporary files, only a single pass initializing everything (e.g. only pinging the registry once, and fetching the manifest/config/signatures once), and automatically ensure that e.g. a copy from a `:latest` tag keeps consistently using the same image, even if the `latest` tag is redirected while copying the big blobs.

The code to copy into `ostree` storage has similarly been converted from an external program using `skopeo inspect` and `skopeo layers` into a native destination (initially calling out `ostree` CLI, later converted to call in-process libraries).

Would something like that make sense for `Nix`? It would be perfectly fine for `PutBlob` to be a 10-line callout to an external process, or a separately maintained Golang package, for example.

(Sure, that may be too much work, or add too much friction to your development process at this time.)

**Comment by nlewo** [comment]
Since Nix is a build system, we generally prefer to let Nix build stuffs since it does this pretty well:) So, I would like to let Nix build an image from the image dependencies which are layers, config and manifest.
This is a common pattern in the Nix ecosystem. For instance, we have a tool called `go2nix` that takes a go project as input and generates a Nix expression for each go dependency (which is not vendorized). There are same kind of tools for Python, Rust...
I'm thinking about same kind of tool for container images: a tool that generates Nix expressions to build an image.
So, unlike `ostree`, we can not implement this in `skopeo`.

I've tryied the `layers` command and it seems this is exactly what I need! In fact, I don't really need to download the config and the manifest independently.
Would it be possible to revert the deprecation of the `layers` command? 
Or is there any other plans regarding this feature?

**Comment by mtrmac** [comment]
I don’t know of any more plans for `skopeo layers` (in particular, there is not a set removal schedule) — but ultimately it seems like such a trivial wrapper around c/image that anyone could re-implement / resurrect it again if that happened.

A more complete history is in https://github.com/projectatomic/skopeo/pull/242 and https://github.com/projectatomic/skopeo/pull/264 ; and an old implementation of precisely this RFC is available in https://github.com/containers/image/pull/159/files .

The trouble with `skopeo layers` is that it is literally exposing a low-level implementation aspect, unlike `skopeo copy`, which is intended to be a high-level tool that takes care of all the details for the user.

Notably, `skopeo inspect` does not do any signature verification, and `skopeo layers` does not verify the downloaded blobs against their supposed digests.  So, in a manually-scripted `inspect`+`layers` implementation, even a _name_`@sha256:`_digest_ reference does not protect the user against a MITM, or a malicious registry/cache, from substituting the image contents with something unwanted!

I suppose the verification could be done outside of `skopeo` as well, using `skopeo` only as a raw docker/distribution client or something like that… but that would make the `skopeo` capabilities pretty dangerous for uninformed users; I’d be tempted to recommend writing a separate Nix-specific containers/image client which provides this raw access, instead of exposing that in `skopeo`. Of course, I still don’t really understand the problem space :)

**Comment by nlewo** [comment]
In our case, we don't really care about layer signatures since we must provide the hash of the layer in the Nix expression. This hash is computed in a previous step, a step that relies on the signature of the image but not on the `layers` command.

I understand that you don't want to expose the `layers` command to end users. FYI, as a end user, I didn't know it:) So it would be nice if this command could stay hidden.

Thanks for mentioned posts and for your explanations.
I then close this ticket since I get enough information for now.
