### ISSUE TITLE
Multitag documentation

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [projectatomic/skopeo#513]
## Problem description
Copying a container image build with the `--additional-tag` flag does not add the additional tag.
Only the tag specified in the `<destination>` field is visible in the registry.

## Expected behaviour
Based on the discussion of #501, I would expect the `skopeo-copy` to copy the container image build with both tags. 

## My Environment
I have an Artifactory private registry with 2 folders: `<src>` and `<dst>`.
I execute the following:
```bash
skope copy docker://<src>:<old_tag> docker://<dst>:<new_tag> --additional-tag=<dst>:latest --screds=... --dcreds=...
```

Which results in the following:
```bash
Getting image source signatures
Skipping fetch of repeat blob sha256:ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28
Copying config sha256:3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353
 0 B / 1.48 KB [------------------------------------------------------------] 0s
Writing manifest to image destination
Storing signatures
```

I would assume all went well, because it is the same output as for when a single tag copy is made with Skopeo, unfortunately I will only see a container image build tagged with `<new_tag>`, none with `latest`. 

For reference, I am using the following Skopeo version: `0.1.31-dev`

Thanks in advance

**Comment by vrothberg** [comment]
## --additional-tag flag
At the moment, the `--additional-tag` flag only works for the `docker-archive` transport (as mentioned in the help message `skopeo copy --help` and the pull request). For all other transports, the flag has no effect, as you describe in your issue.

You can try it for docker archives with something as follows:
``` bash
skopeo copy docker://alpine:latest docker-archive:foo.tar:alpine:latest --additional-tag alpine:foo
```

In the `manifest.json` file in `foo.tar` you can find the additional tag.

## multitag push
The example you describe in this issue refers to pushing an image with multiple tags to a registry. Although it is technically possible to do that, it is something still not supported by Docker itself. However, I am not overly familiar with registry-related code of skopeo, so I cannot answer how much work it would be to support that with skopeo.

**Comment by nlewo** [comment]
I also use Skopeo to push several tags to a registry and this is not really efficient I need to push several times the image (included all layers).

With Docker, you can do something such as:
```
docker push myregistry/image:tag1
docker tag myregistry/image:tag1 myregistry/image:tag2
docker push myregistry/image:tag2
```
Since Docker is able to know already sent layers, this is quite efficient because layers are not sent by the second `push`. This is not the case with Skopeo. So, this `additional-tag` would be a good alternative to me:)

**Comment by CamiloGarciaLaRotta** [comment]
Thanks for the explanation @vrothberg and thanks for the workaround @nlewo 
I'll proceed with the `docker tag` approach

**Comment by mtrmac** [comment]
As @vrothberg says, the `--additional-tag` option is documented for `docker-archive:` only.

---

> Since Docker is able to know already sent layers, this is quite efficient because layers are not sent by the second `push`. This is not the case with Skopeo. So, this `additional-tag` would be a good alternative to me:)

True—but I’d rather have a generic mechanism that can avoid re-pushing layers in all situations transparently (see https://github.com/containers/image/issues/312 , https://github.com/containers/image/issues/104) than a local specific `--additional-tag` hack.  `--additional-tag` makes sense for `docker-archive:`, because it is a single file which may be very expensive to update; this is not really the case for `docker://`

> I also use Skopeo to push several tags to a registry and this is not really efficient I need to push several times the image (included all layers).
>
> With Docker, you can do something such as:
> ```
> docker push myregistry/image:tag1
> docker tag myregistry/image:tag1 myregistry/image:tag2
> docker push myregistry/image:tag2
> ```
FWIW this can be done reasonably efficiently with `skopeo` as well:
```
# create myregistry/image:tag1 somehow
skopeo copy docker://myregistry/image:tag1 docker://myregistry/image:tag2
```
This will require a few round-trips, but the big layers will not be copied again (at least as long as `tag1` and `tag2` are in the same repo); and it can be done without changing the Docker daemon tags on the local host.
